### ISSUE TITLE
Kafka 0.9 support

### ISSUE THREAD

**Issue by dbeckham** [damienclaveau/kafka-graphite#19]
It looks like this is broken in Kafka 0.9.x, complaining of a dimension error. Any idea how soon you this will be updated for the latest version of Kafka?

Error message: 
```
ERROR Dimensions [count, meanRate, rate1m, rate5m, rate15m] (com.criteo.kafka.KafkaGraphiteMetricsReporter)
```

**Comment by damienclaveau** [comment]
This error log is a residual debugging trace. Fixed in https://github.com/damienclaveau/kafka-graphite/commit/6d43b5b98c865a0557a751f2a1cc0047702141a3

The plug-in is fully functional with Kafka 0.9
