### ISSUE TITLE
Broker ID (hostname) within metric-key

### ISSUE THREAD

**Issue by ChristianKniep** [damienclaveau/kafka-graphite#20]
Hey there,

even without me beeing a java-guys, I was able to put it to work... :)
https://github.com/qnib/docker-kafka-metrics/tree/0.10.0.0

What I would like to see is that the metrics keys include the BrokerID or the hostname to distinguish mutliple broker.
Or do I understand the metric output wrong?
![screen shot 2016-07-05 at 17 56 09](https://cloud.githubusercontent.com/assets/1420201/16590902/bef2fc34-42d9-11e6-9a38-b35c70fbe95b.png)

Thx!

**Comment by msiuts** [comment]
You can set the property `kafka.graphite.metrics.group` to something that includes your broker id and/or the hostname. Should be easy in your template.

**Comment by ChristianKniep** [comment]
Sweet, first thing in the morning... 
Thx!
