### ISSUE TITLE
Unable to send metrics to graphite

### ISSUE THREAD

**Issue by amoghe** [damienclaveau/kafka-graphite#6]
I'm unable to see any metrics on graphite. I'm seeing these messages from kafka on startup:

```
[2015-04-09 23:16:05,717] INFO Verifying properties (kafka.utils.VerifiableProperties)
[2015-04-09 23:16:05,742] INFO Property broker.id is overridden to 0 (kafka.utils.VerifiableProperties)
[2015-04-09 23:16:05,742] WARN Property kafka.graphite.metrics.group is not valid (kafka.utils.VerifiableProperties)
[2015-04-09 23:16:05,743] WARN Property kafka.graphite.metrics.host is not valid (kafka.utils.VerifiableProperties)
[2015-04-09 23:16:05,743] WARN Property kafka.graphite.metrics.port is not valid (kafka.utils.VerifiableProperties)
[2015-04-09 23:16:05,743] WARN Property kafka.graphite.metrics.reporter.enabled is not valid (kafka.utils.VerifiableProperties)
[2015-04-09 23:16:05,743] WARN Property kafka.metrics.reporters is not valid (kafka.utils.VerifiableProperties)
```

Also, this is what kafka launches with (`java.class.path`). I've split it on `:` so its easier to read. As you can see, the metrics jar as well as the kafka-graphite-1.0.0 jar are both present.
```
/opt/kafka/bin/../core/build/dependant-libs-2.10.4*/*.jar
:/opt/kafka/bin/../examples/build/libs//kafka-examples*.jar
:/opt/kafka/bin/../contrib/hadoop-consumer/build/libs//kafka-hadoop-consumer*.jar
:/opt/kafka/bin/../contrib/hadoop-producer/build/libs//kafka-hadoop-producer*.jar
:/opt/kafka/bin/../clients/build/libs/kafka-clients*.jar
:/opt/kafka/bin/../libs/jopt-simple-3.2.jar
:/opt/kafka/bin/../libs/kafka_2.10-0.8.2.0.jar
:/opt/kafka/bin/../libs/kafka_2.10-0.8.2.0-javadoc.jar
:/opt/kafka/bin/../libs/kafka_2.10-0.8.2.0-scaladoc.jar
:/opt/kafka/bin/../libs/kafka_2.10-0.8.2.0-sources.jar
:/opt/kafka/bin/../libs/kafka_2.10-0.8.2.0-test.jar
:/opt/kafka/bin/../libs/kafka-clients-0.8.2.0.jar
:/opt/kafka/bin/../libs/kafka-graphite-1.0.0.jar
:/opt/kafka/bin/../libs/log4j-1.2.16.jar
:/opt/kafka/bin/../libs/lz4-1.2.0.jar
:/opt/kafka/bin/../libs/metrics-core-2.2.0.jar
:/opt/kafka/bin/../libs/metrics-graphite-2.2.0.jar
:/opt/kafka/bin/../libs/scala-library-2.10.4.jar
:/opt/kafka/bin/../libs/slf4j-api-1.7.6.jar
:/opt/kafka/bin/../libs/slf4j-log4j12-1.6.1.jar
:/opt/kafka/bin/../libs/snappy-java-1.1.1.6.jar
:/opt/kafka/bin/../libs/zkclient-0.3.jar
:/opt/kafka/bin/../libs/zookeeper-3.4.6.jar
:/opt/kafka/bin/../core/build/libs/kafka_2.10*.jar (org.apache.zookeeper.ZooKeeper)
```

Any pointers to what I'm possibly missing?

**Comment by britishdan** [comment]
+1
I also get those messages.
After a little while, I start getting these in the log:
WARN Error writing to Graphite: Operation timed out (com.yammer.metrics.reporting.GraphiteReporter)

**Comment by harshalvjoshi** [comment]
Hi,

Is there document where I can have end-to-end instruction to send kafka matrices to graphite. 
https://github.com/damienclaveau/kafka-graphite the changes related to broker is given. how to connect to graphite server from here. if any configuration required ?

**Comment by waltari2001** [comment]
Same problem here. It's only happening on one node out of a 6 nodes kafka cluster.

**Comment by amoghe** [comment]
I ended up going with this [https://github.com/airbnb/kafka-statsd-metrics2] instead

**Comment by britishdan** [comment]
In my scenario, the fault was my own.
The graphite port wasn't available to me. Now that telnet works, the GraphiteReporter connects and I get all the matrices (despite the WARNings).

**Comment by damienclaveau** [comment]
Thanks Dan, the most frequent errors come from network connectivity, not from the component.
In my test configuration, I don't reproduce the problems above, sorry.

**Comment by obazoud** [comment]
Work fine on kafka 0.8.1.1 and Graphite 0.9.12

**Comment by Govind-Bhone** [comment]
@damienclaveau will this work with kafka 0.11.0.2 version . Also I am getting broker.id configuration error when i have not added this configuration in server.properties file and used broker.id.generation.enable=true instead
