### ISSUE TITLE
Upgrade to Kafka 0.8.2.x

### ISSUE THREAD

**Issue by obazoud** [damienclaveau/kafka-graphite#9]
see forks.

**Comment by marcinszymaniuk** [comment]
Would it be enough to just update maven dependencies of kafka?

**Comment by msiuts** [comment]
As long as you do not use the uber-jar it will be compatibel with kafka 0.8.2 out of the box.

**Comment by damienclaveau** [comment]
Done, with the helpful work made by msiuts/emetriq
